services:
  redmine:
    image: redmine:6.0
    restart: always
    ports:
      - "8080:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_SECRET_KEY_BASE: supersecretkey_change_in_production_1234567890
    volumes:
      - redmine_files:/usr/src/redmine/files
      - ./plugins:/usr/src/redmine/plugins
      - ./public/themes:/usr/src/redmine/public/themes
      - ./app/assets/stylesheets:/usr/src/redmine/app/assets/stylesheets
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redmine_files:
  postgres_data:
